site_name: "docs-poc-svc"
site_description: "Documents examples"

nav:
  - Introduction: index.md
  - Soap:
      - ifaz_interfaz_local.md
  - Rest:
      - tab_funcional.md

plugins:
  - techdocs-core
